log:
  - writer: file
    level: info
    writer_config:
      filename: "info.log"
      log_path: "log"
      max_backups: 1
      max_age: midnight
      format_config:
        time_fmt: "%Y-%m-%d %H:%M:%S"
        fmt: "[%(asctime)s][%(levelname)s][%(filename)s:%(lineno)s][%(process)d][%(message)s]"

workers:
  - host: local
    status: /status
    task: /task
    con: 1
  - host: 127.0.0.1
    status: /status
    task: /task
    con: 1